### ISSUE TITLE
missing licence

### ISSUE THREAD

**Issue by mjrider** [roydejong/ing-card-to-mt940#1]
Hello,

currently the projects does not define a licence the code is released under.
Any change on licencing it under something like GPL or MIT?

regards

Robbert

**Comment by roydejong** [comment]
I have added a license file. Please feel free to use any code here under MIT license.

Out of curiosity, what are you looking to use this code for?

**Comment by mjrider** [comment]
atm, importing ing and knab transactions into moneybird
currently in a mostly hacky version, code cleanups are needed if i want to include them both
